# Generated by Django 4.2.5 on 2023-09-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoviz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pics',
            name='user',
        ),
        migrations.AddField(
            model_name='pics',
            name='name',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
