# Generated by Django 4.2.5 on 2023-09-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algoviz', '0003_pics_fno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='algo',
        ),
    ]
