# Generated by Django 4.2.5 on 2023-09-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoviz', '0005_pics_gif_alter_pics_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='frame',
            field=models.ImageField(upload_to='midea/algoviz/images/'),
        ),
        migrations.AlterField(
            model_name='pics',
            name='gif',
            field=models.ImageField(upload_to='midea/algoviz/images/'),
        ),
    ]
